autoCorrect: false

build:
  maxIssues: 1

potential-bugs:
  active: true

exceptions:
  active: true

empty:
  active: true

complexity:
  active: true
  LongMethod:
    threshold: 20
  LongParameterList:
    threshold: 5
  LargeClass:
    threshold: 150
  ComplexMethod:
    threshold: 10
  TooManyFunctions:
    threshold: 10
    active: false
  ComplexCondition:
    threshold: 5
  NestedBlockDepth:
    threshold: 5

code-smell:
  active: true
  FeatureEnvy:
    threshold: 0.5
    weight: 0.45
    base: 0.5

formatting:
  active: true
  useTabs: true
  autoCorrect: true
  Indentation:
    active: false
  ConsecutiveBlankLines:
  MultipleSpaces:
  SpacingAfterComma:
  SpacingAfterKeyword:
  SpacingAroundColon:
  SpacingAroundCurlyBraces:
  SpacingAroundOperator:
  TrailingSpaces:
  UnusedImports:
  OptionalSemicolon:
  OptionalUnit:

style:
  active: true
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false
  NamingConventionViolation:
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
    constantPattern: '^([A-Z_0-9]*|serialVersionUID)$'
    methodPattern: '^[a-z$][a-zA-Z$0-9]*$'
    classPattern: '([A-Z][a-z0-9]*)+'
  ReturnCount:
    active: true
    max: 3
  FunctionMaxLength:
    active: true
    maximumFunctionNameLength: 40
  VariableMinLength:
    active: false

comments:
  active: true
  CommentOverPrivateMethod:
    active: true
  CommentOverPrivateProperty:
    active: true
  NoDocOverPublicClass:
    active: false
  NoDocOverPublicMethod:
    active: false
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false